### ISSUE TITLE
Bug: 1s is not valid signature

### ISSUE THREAD

**Issue by Truemedia** [wolfika/playing-card-signature#2]
I get an error when using this signature even though it looks like it should be valid.

**Comment by Truemedia** [comment]
Ignore this forgot you don't actually have a 1 in standard decks

**Comment by wolfika** [comment]
Yes, you don't have 1 in a standard deck.
Actually found that in the README.md I accidentally listed `1` as a valid rank, whereas it is not. Removed it, thanks for the heads up!
